services:
  weather-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEYS=${API_KEYS}
      - USER_AGENT=${USER_AGENT}
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: always
    networks:
      - dokploy-network
      - containers
    volumes:
      - weather-mcp-server:/app/logs

networks:
  containers:
    external: true
  dokploy-network:
    external: true

volumes:
  weather-mcp-server:
